CREATE DATABASE IF NOT EXISTS top_college CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE top_college;

CREATE TABLE IF NOT EXISTS colleges (
    id INT AUTO_INCREMENT PRIMARY KEY,
    college_name VARCHAR(255) DEFAULT NULL,
    clg_name VARCHAR(200) DEFAULT NULL,
    short_name VARCHAR(100) DEFAULT NULL,
    title VARCHAR(255) DEFAULT NULL,
    heading VARCHAR(255) DEFAULT NULL,
    short_description TEXT DEFAULT NULL,
    long_description TEXT DEFAULT NULL,
    description LONGTEXT DEFAULT NULL,
    course_name VARCHAR(200) DEFAULT NULL,
    courses TEXT DEFAULT NULL,
    course_duration VARCHAR(100) DEFAULT NULL,
    batch VARCHAR(100) DEFAULT NULL,
    fees VARCHAR(100) DEFAULT NULL,
    facilities TEXT DEFAULT NULL,
    address TEXT DEFAULT NULL,
    state VARCHAR(100) DEFAULT NULL,
    city VARCHAR(100) DEFAULT NULL,
    pincode VARCHAR(20) DEFAULT NULL,
    logo VARCHAR(255) DEFAULT NULL,
    photos TEXT DEFAULT NULL,
    images LONGTEXT DEFAULT NULL,
    important_links LONGTEXT DEFAULT NULL,
    source_pages LONGTEXT DEFAULT NULL,
    facebook VARCHAR(255) NOT NULL DEFAULT '',
    instagram VARCHAR(255) NOT NULL DEFAULT '',
    twitter VARCHAR(255) NOT NULL DEFAULT '',
    linkedin VARCHAR(255) NOT NULL DEFAULT '',
    college_id INT DEFAULT NULL,
    added_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    is_top INT DEFAULT 0,
    slug VARCHAR(255) DEFAULT NULL,
    website VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(100) DEFAULT NULL,
    latitude DECIMAL(10,8) DEFAULT NULL,
    longitude DECIMAL(11,8) DEFAULT NULL,
    seo_title VARCHAR(255) DEFAULT NULL,
    seo_description TEXT DEFAULT NULL,
    seo_keywords TEXT DEFAULT NULL,
    seo_content LONGTEXT DEFAULT NULL,
    admission_process TEXT DEFAULT NULL,
    placement_info TEXT DEFAULT NULL,
    about_college TEXT DEFAULT NULL,
    scrape_status ENUM('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
    scrape_error TEXT DEFAULT NULL,
    scrape_started_at DATETIME DEFAULT NULL,
    scraped_at DATETIME DEFAULT NULL,
    UNIQUE KEY uq_colleges_slug (slug),
    KEY idx_colleges_status (scrape_status)
);

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    course_interest VARCHAR(255) DEFAULT NULL,
    city VARCHAR(100) DEFAULT NULL,
    state VARCHAR(100) DEFAULT NULL,
    latitude DECIMAL(10,8) DEFAULT NULL,
    longitude DECIMAL(11,8) DEFAULT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_students_phone (phone),
    KEY idx_students_course (course_interest),
    KEY idx_students_location (latitude, longitude)
);

CREATE TABLE IF NOT EXISTS lead_distribution (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    college_id INT NOT NULL,
    distributed_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'sent',
    distance_km DECIMAL(8,2) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_student_college (student_id, college_id),
    KEY idx_lead_college_date (college_id, distributed_date),
    KEY idx_lead_student (student_id),
    CONSTRAINT fk_lead_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_lead_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE
);
